import json
import os
import zipfile
import tempfile

from fastapi import APIRouter, Depends
from fastapi.responses import FileResponse
from sqlalchemy.orm import Session

from database.database import get_db
from models.agent_output import AgentOutput

router = APIRouter(
    prefix="/export",
    tags=["Export"]
)


@router.get("/{project_id}")
def export_project(
    project_id: int,
    db: Session = Depends(get_db)
):
    outputs = db.query(AgentOutput).filter(
        AgentOutput.project_id == project_id
    ).all()

    temp_dir = tempfile.mkdtemp()

    # Create text files
    for output in outputs:
        filename = os.path.join(
            temp_dir,
            f"{output.agent_name}.txt"
        )

        with open(filename, "w", encoding="utf-8") as file:
            file.write(output.output)

            readme = os.path.join(temp_dir, "README.md")

            with open(readme, "w", encoding="utf-8") as file:
                    file.write(f"""# CodeForge AI Export

                Project ID: {project_id}

                This project was generated using CodeForge AI.

                Contents:

                - Research
                - Architecture
                - Coding
                - Testing
                - Documentation

                Generated by:
                CodeForge AI Multi-Agent Workspace
                """)
                    
                    metadata = {
                        "project_id": project_id,
                        "generated_by": "CodeForge AI",
                        "agents": [
                            output.agent_name
                            for output in outputs
                        ],
                        "total_outputs": len(outputs)
                    }

                    metadata_file = os.path.join(
                        temp_dir,
                        "metadata.json"
                    )

                    with open(metadata_file, "w") as file:
                        json.dump(metadata, file, indent=4)

    zip_filename = f"project_{project_id}.zip"

    zip_path = os.path.join(
        temp_dir,
        zip_filename
    )

    with zipfile.ZipFile(
        zip_path,
        "w",
        zipfile.ZIP_DEFLATED
    ) as zipf:

        for file in os.listdir(temp_dir):

            if file.endswith((".txt", ".md", ".json", ".pdf")):

                zipf.write(
                    os.path.join(temp_dir, file),
                    arcname=file
                )

    return FileResponse(
        zip_path,
        filename=zip_filename,
        media_type="application/zip"
    )