#!/usr/bin/env python3
"""
Test script for AI Chat Title Generation Feature
Tests that chat titles are automatically generated by Gemini API
"""

import requests
import json
import time
from urllib.parse import urlencode

BASE_URL = "http://127.0.0.1:8000"

def test_title_generation():
    """Test the automatic chat title generation feature"""
    
    print("\n" + "="*60)
    print("🚀 TESTING AI CHAT TITLE GENERATION")
    print("="*60 + "\n")
    
    # Test cases with different message types
    test_cases = [
        {
            "message": "Build a React dashboard with authentication and real-time charts",
            "expected": "React Dashboard"
        },
        {
            "message": "Create a portfolio website to showcase my projects",
            "expected": "Portfolio Website"
        },
        {
            "message": "Build a FastAPI REST API for a todo application",
            "expected": "FastAPI API"
        },
        {
            "message": "Create a resume builder application with PDF export",
            "expected": "Resume Builder"
        }
    ]
    
    for idx, test_case in enumerate(test_cases, 1):
        print(f"\n📝 Test Case {idx}")
        print(f"   Message: {test_case['message'][:50]}...")
        print(f"   Expected Title Pattern: {test_case['expected']}")
        
        try:
            # Create a new chat
            chat_response = requests.post(f"{BASE_URL}/chat/new", timeout=5)
            chat_response.raise_for_status()
            chat_data = chat_response.json()
            chat_id = chat_data['id']
            initial_title = chat_data['title']
            
            print(f"   ✓ Chat created (ID: {chat_id})")
            print(f"   ✓ Initial title: '{initial_title}'")
            
            # Send message to trigger title generation
            print(f"   ⏳ Sending message to generate title...")
            send_response = requests.post(
                f"{BASE_URL}/chat/send/{chat_id}",
                json={"message": test_case['message']},
                timeout=45  # Give Gemini API time to respond
            )
            send_response.raise_for_status()
            send_data = send_response.json()
            new_title = send_data['title']
            
            print(f"   ✅ AI Generated Title: '{new_title}'")
            
            # Check if title changed
            if new_title != initial_title and new_title != "New Chat":
                print(f"   ✓ Title successfully changed!")
            else:
                print(f"   ✗ Title did not change (still: '{new_title}')")
                
        except requests.exceptions.Timeout:
            print(f"   ⚠️  Request timed out (Gemini API may be slow)")
        except requests.exceptions.ConnectionError:
            print(f"   ✗ Connection error - is the backend running?")
        except Exception as e:
            print(f"   ✗ Error: {str(e)}")
    
    print("\n" + "="*60)
    print("✅ Test completed!")
    print("="*60 + "\n")

if __name__ == "__main__":
    test_title_generation()
