from services.project_generator import ProjectGenerator

generator = ProjectGenerator("ResumeBuilder")

# Create folder structure
generator.create_structure()

# Create README
generator.write_file(
    "README.md",
    "# Resume Builder\n\nGenerated by CodeForge AI"
)

# Create React App file
generator.write_file(
    "frontend/App.tsx",
    """export default function App() {
    return <h1>Hello from CodeForge AI</h1>;
}
"""
)

# Create FastAPI file
generator.write_file(
    "backend/main.py",
    """from fastapi import FastAPI

app = FastAPI()

@app.get("/")
def home():
    return {"message": "Hello"}
"""
)

print("✅ Project generated successfully!")